version: 0.2
env:
  parameter-store:
    SARJIS_REGION: "SARJIS_REGION"
    ADMIN_ACCOUNT_ID: "ADMIN_ACCOUNT_ID"
    SARJIS_REPO_NAME: "SARJIS_REPO_NAME"
    SARJIS_IMAGE_TAG: "SARJIS_IMAGE_TAG"

phases:
  install:
    #runtime-versions:
    #  docker: 18
    commands:
      # Install dependencies needed for running tests
      # - pip install --upgrade pip
      # - pip install -r requirements.txt
      # - sudo apt-get update
      # - sudo apt-get install docker.io -y

  pre_build:
    commands:
      - aws ecr get-login-password --region $SARJIS_REGION | docker login --username AWS --password-stdin $ADMIN_ACCOUNT_ID.dkr.ecr.$SARJIS_REGION.amazonaws.com

  build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
     #- sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      - docker build -t $SARJIS_REPO_NAME:$SARJIS_IMAGE_TAG .
      - docker tag $SARJIS_REPO_NAME:$SARJIS_IMAGE_TAG $ADMIN_ACCOUNT_ID.dkr.ecr.$SARJIS_REGION.amazonaws.com/$SARJIS_REPO_NAME:$SARJIS_IMAGE_TAG      

#      - apt-get install jq -y
#      - ContainerName="ecr-sarjis-repo"
#      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
#      - cat $CODEBUILD_SRC_DIR/imageDetail.json
#      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
#      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ADMIN_ACCOUNT_ID.dkr.ecr.$SARJIS_REGION.amazonaws.com/$SARJIS_REPO_NAME:$SARJIS_IMAGE_TAG
      - IMAGE_URI=$ADMIN_ACCOUNT_ID.dkr.ecr.$SARJIS_REGION.amazonaws.com/$SARJIS_REPO_NAME:$SARJIS_IMAGE_TAG  
      - printf '[{"name":%s,"imageUri":%s}]' $SARJIS_REPO_NAME $IMAGE_URI > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
#    name: imagedefinitions.json
#    discard-paths: yes

