version: '3.1'

services:
  database:
    image: sarjis-db:latest
    container_name: database
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    networks:
      - sarjisnetwork

  sarjis:
    image: sarjis-service:latest
    # build:
    #   context: ./service
    #   dockerfile: Dockerfile
    container_name: sarjis
    ports:
      - 8000:8000
    networks:
      sarjisnetwork:
        aliases:
          - sarjis_backend
    depends_on:
      - database

  nginx:
    image: sarjis-web:latest
    container_name: nginx
    # volumes:
    #   - ./:/var/www/
    #   - ./web/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - sarjisnetwork
    depends_on:
      - sarjis

networks:
  sarjisnetwork: {}
