version: '3.1'

services:
  database:
    image: postgres:alpine3.17
    container_name: database
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - sarjisnetwork

  sarjis:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: sarjis
    networks:
      sarjisnetwork:
        aliases:
          - sarjis_backend
    depends_on:
      - database

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./:/var/www/
      - ./httpserver/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - sarjisnetwork
    depends_on:
      - sarjis

networks:
  sarjisnetwork: {}
